postgis:
  container_name: learning-postgis-instance
  image: postgis/postgis:12-3.0-alpine
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 10s
    timeout: 5s
    retries: 5
  environment:
    # The default Postgres image exposes a number of environmental variables
    # that allow you to configure the container's behavior, without writing
    # any additional code. Specify the name of your database, and any other
    # variables, here. https://hub.docker.com/_/postgres/#environment-variables
    POSTGRES_DB: postgis_in_action
    POSTGRES_PASSWORD: postgres
  volumes:
    # By default, Postgres instantiates an anonymous volume. Use a named
    # one, so your data persists beyond the life of the container. See this
    # post for a discussion of the pitfalls of Postgres and anonymous
    # volumes: https://linuxhint.com/run_postgresql_docker_compose/
    - learning-postgis-instance-data:/var/lib/postgresql/data
  ports:
    - 32001:5432

